package com.github.anguzudaniel.profanity

val profaneWords = listOf(
    "love",
    "fuck",
    "stupid",
    "nigga",
    "ugly",
    "expletive",
    "curse",
    "swearword",
    "vulgar",
    "obscene",
    "offensive",
    "crude",
    "vile",
    "indecent",
    "filthy",
    "abusive",
    "vulgarism",
    "cuss",
    "naughty",
    "dirty",
    "lewd",
    "nasty",
    "impolite",
    "vulgarity",
    "improper",
    "taboo",
    "repugnant"
)
